<a href="https://colab.research.google.com/github/khushidevi7051-cmd/AI-ML-Project/blob/main/MyInternship_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Project:**  Pneumonia Detection via Chest X-Ray Classification



##***Project Overview***
 This project establishes an end-to-end Machine Learning pipeline to classify chest X-ray images into two binary categories: **Normal (0)** and **Pneumonia (1)**.

 The Pipeline handles:

*  **Image Ingestion & Preprocessing**
(grayscale conversion,resizing,flattening)
*   **Dataset Partitioning**
(Stratified train/test split)
*   **Deep Learning Model Construction**
(Multi-Layer Perceptron using Keras)
*   **Itervative Model Training & Performance Evaluation**





#**Step-by-Step Implementation**

##Step 1: Import Required Libraries
You need to import core utilities for file handling, numerical operations, image processing, and deep learning.

In [ ]:
import os
import numpy as np
from PIL import Image
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

##Step 2: Download Dataset From GitHub

In [ ]:
!git clone https://github.com/YBIFoundation/ComputerVision.git

Cloning into 'ComputerVision'...
remote: Enumerating objects: 384, done.
remote: Counting objects: 100% (246/246), done.
remote: Compressing objects: 100% (236/236), done.
remote: Total 384 (delta 68), reused 10 (delta 10), pack-reused 138 (from 1)
Receiving objects: 100% (384/384), 47.25 MiB | 23.92 MiB/s, done.
Resolving deltas: 100% (72/72), done.


##Step 3: Define Dataset Directiories
You set the file paths pointing to where your source images are saved on your computer or cloud environment.

In [ ]:
normal_dir = '/content/ComputerVision/NormalXray'
pneumonia_dir='/content/ComputerVision/PneumoniaXray'

##Step 4: Initialize Variables and Constants
You define the target size for the images and create empty lists to hold your processed data.

In [ ]:
IMG_SIZE=(64,64)
X=[]
y=[]

##Step 5: Process the "Normal" Images
You loop through every image file inside the normal directory to read,clean and store it.

In [ ]:
for file in os.listdir(normal_dir):
    img = Image.open(os.path.join(normal_dir, file)).convert("L")
    img= img.resize(IMG_SIZE)
    X.append(np.array(img).flatten())
    y.append(0)

##Step 6: Process the "Pneumonia" Images
You repeat the exact same processing loop for the diseased X-Ray images,but assign them a different label.

In [ ]:
for file in os.listdir(pneumonia_dir):
    img = Image.open(os.path.join(pneumonia_dir, file)).convert("L")
    img= img.resize(IMG_SIZE)
    X.append(np.array(img).flatten())
    y.append(1)

##Step 7: Convert Lists to Numpy Arrays
Python lists are slow for machine learing, so you tranform them into highly optimized NumPy arrays.

In [ ]:
X=np.array(X)
y=np.array(y)


##Step 8: Verify Data Shapes
You print out the final structure of your dataset to ensure everything loaded correctly before building a model.

In [ ]:
print(X.shape)
print(y.shape)

(100, 4096)
(100,)


##Step 9: Data Inspection and Feature Verification

In [ ]:
print("Total flattened pixels:",64*64)
print("\nFirst image pixels values\n:",X)
print("\nAll target labels\n:", y)



Total flattened pixels: 4096

First image pixels values
: [[213 204 197 ...   9  11  13]
 [  0   0   0 ...   0   0   0]
 [  0  69  84 ...   0   0   4]
 ...
 [ 63  52  32 ...   0   0   0]
 [114  40  53 ...  17  19  19]
 [ 47  55  67 ...  45  45  46]]

All target labels
: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


##Step 10: Split Data into Training and Testing Sets
You divide your dataset into two parts: one to train the model,and one to test how well it learned.

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=2529, stratify=y)

##Step 11: Initialize the Sequential Model
You create a linear backbone container where neural network layers can be stacked on top of each other.

In [ ]:
model = Sequential()

##Step 12: Add Hidden Layers
You add fully connected(Dense) layers that will look for patterns in the flattened image pixel data.

In [ ]:
model.add(Dense(128,activation='relu'))
model.add(Dense(64,activation='relu'))

##Step 13: Add the Output Layer
You add final layer with single neuron to give the final classification answer.

In [ ]:
model.add(Dense(1,activation='sigmoid'))

##Step 14: Compile the Model
Before training you configure how the model learns by setting its mathematical goals and evaluation metrics.

In [ ]:
model.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])

##Step 15:Train (Fit) the Model
You feed the training data into the network so it can learn by trial and error.

In [ ]:
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 4s 78ms/step - accuracy: 0.5733 - loss: 83.1401 
Epoch 2/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 1.0000 - loss: 0.0000e+00 
Epoch 3/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 1.0000 - loss: 0.0000e+00
Epoch 4/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0000e+00 
Epoch 5/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - accuracy: 1.0000 - loss: 0.0000e+00
Epoch 6/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 1.0000 - loss: 0.0000e+00
Epoch 7/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 1.0000 - loss: 0.0000e+00 
Epoch 8/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 1.0000 - loss: 0.0000e+00
Epoch 9/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 1.0000 - loss: 0.0000e+00
Epoch 10/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 1.0000 - loss: 0.0000e+00


##Step 16: Review Model Structure & Predict
You check the final blueprint layout of your network and generate predictions on the unseen test images.

In [ ]:
model.summary()
y_pred=np.round(model.predict(X_test))

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │       524,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,598,213 (6.10 MB)

 Trainable params: 532,737 (2.03 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,065,476 (4.06 MB)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step


##Step 17: Generate a Classification Report
You import and print a detailed breakdown of how well your model performed on the test data.

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        25

    accuracy                           1.00        25
   macro avg       1.00      1.00      1.00        25
weighted avg       1.00      1.00      1.00        25

